# Generated by Django 3.0.3 on 2020-02-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_login',
            name='permission_id',
            field=models.PositiveIntegerField(),
        ),
    ]
