# Generated by Django 3.0.3 on 2020-04-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_o_delivery',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_from', models.TextField()),
                ('c_to', models.TextField()),
                ('d_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='billDetails',
        ),
        migrations.RemoveField(
            model_name='consigndetails',
            name='c_date',
        ),
        migrations.RemoveField(
            model_name='consigndetails',
            name='c_price',
        ),
        migrations.RemoveField(
            model_name='consigndetails',
            name='order_id',
        ),
    ]
