# Generated by Django 3.0.3 on 2020-06-12 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0002_auto_20200612_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consign_details',
            name='c_from',
        ),
        migrations.RemoveField(
            model_name='t_o_delivery',
            name='c_from',
        ),
        migrations.RemoveField(
            model_name='t_o_delivery',
            name='d_sh_date',
        ),
        migrations.AddField(
            model_name='consign_details',
            name='pkg_r_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
