# Generated by Django 3.0.3 on 2020-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0002_auto_20200412_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_o_delivery',
            name='d_sh_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
