# Generated by Django 3.0.3 on 2020-06-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0003_auto_20200612_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t_o_delivery',
        ),
    ]
