# Generated by Django 3.0.3 on 2020-06-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0003_auto_20200413_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='consign_pkg',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_id', models.CharField(max_length=20)),
                ('order_id', models.IntegerField()),
                ('pkg_r_date', models.DateField()),
                ('d_sh_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='state_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('state_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='temp_pkg_model',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=50)),
                ('r_city', models.CharField(max_length=30)),
                ('r_state', models.CharField(max_length=30)),
                ('pkg_r_date', models.DateField()),
                ('pkg_weight', models.IntegerField()),
            ],
        ),
    ]
