# Generated by Django 3.0.3 on 2020-03-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0003_auto_20200305_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin_login',
            options={},
        ),
        migrations.AlterModelManagers(
            name='admin_login',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='username',
        ),
    ]
