# Generated by Django 3.0.3 on 2020-03-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0004_auto_20200306_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('permission_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='billDetails',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
                ('b_desc', models.TextField()),
                ('b_amt', models.IntegerField()),
                ('b_ship', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='consignDetails',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_desc', models.TextField()),
                ('c_quan', models.IntegerField()),
                ('c_price', models.IntegerField()),
                ('c_to', models.TextField()),
                ('c_from', models.TextField()),
                ('c_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='employeeDetails',
            fields=[
                ('e_id', models.IntegerField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=45)),
                ('e_mail', models.EmailField(max_length=254)),
                ('e_contact', models.IntegerField()),
                ('e_add', models.TextField()),
                ('e_per_id', models.TextField()),
                ('e_userName', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='transcDetails',
            fields=[
                ('t_id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_amt', models.IntegerField()),
                ('t_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='admin_login',
        ),
    ]
