# Generated by Django 3.0.3 on 2020-04-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0004_consign_pkg'),
    ]

    operations = [
        migrations.AddField(
            model_name='consign_pkg',
            name='s_no',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
