# Generated by Django 3.0.3 on 2020-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0005_t_o_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='consign_details',
            name='pkg_weight',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
