# Generated by Django 3.0.3 on 2020-06-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0006_consign_details_pkg_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_pkg_details',
            name='item_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
