# Generated by Django 3.0.3 on 2020-03-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0006_auto_20200320_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='e_password',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='e_per_id',
            field=models.CharField(default=111111, max_length=6),
            preserve_default=False,
        ),
    ]
