# Generated by Django 3.0.3 on 2020-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0009_per_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_details',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=45)),
                ('s_contact', models.CharField(max_length=10)),
                ('s_add', models.CharField(max_length=100)),
                ('s_city', models.CharField(max_length=30)),
                ('s_pincode', models.IntegerField()),
                ('r_name', models.CharField(max_length=45)),
                ('r_contact', models.CharField(max_length=10)),
                ('r_add', models.CharField(max_length=100)),
                ('r_city', models.CharField(max_length=30)),
                ('r_pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cust_pkg_details',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=45)),
                ('pkg_r_date', models.DateField()),
                ('pkg_r_time', models.TimeField()),
                ('pkg_d_date', models.DateField()),
                ('pkg_d_time', models.TimeField()),
                ('pkg_weight', models.IntegerField()),
                ('pkg_ship_add', models.TextField()),
                ('pkg_ship_city', models.CharField(max_length=45)),
                ('pkg_ship_pincode', models.IntegerField()),
                ('ship_service_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='transc_Details',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tr_id', models.IntegerField()),
                ('t_mode', models.CharField(max_length=20)),
                ('t_amt', models.IntegerField()),
                ('t_date', models.DateField()),
                ('t_time', models.TimeField()),
                ('t_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='adminProfile',
        ),
        migrations.DeleteModel(
            name='transcDetails',
        ),
        migrations.AlterField(
            model_name='per_table',
            name='Description',
            field=models.CharField(max_length=30),
        ),
    ]
