# Generated by Django 3.0.3 on 2020-03-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0009_per_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='per_table',
            name='Description',
            field=models.CharField(max_length=30),
        ),
    ]
