# Generated by Django 3.0.3 on 2020-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoms', '0010_auto_20200403_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_details',
            name='cust_name',
            field=models.CharField(max_length=50),
        ),
    ]
